name = "arc"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
twocore = { git = "https://github.com/hiett/2core", ref = "896b84b4157832e5a471a60e8d04c45205994a4e" }

[dev-dependencies]
