name = "arc_aot"
version = "0.1.0"
target = "erlang"

[dependencies]
arc = { path = ".." }
carder = { git = "https://github.com/scarletindustries/carder", ref = "5ede669462f6ac934897fceba9b77b4c2a5d3e6f" }
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
testkit = { path = "../testkit" }
