#!/usr/bin/env escript
%% -*- erlang -*-
%% usage: escript scripts/gen_names.escript (from repo root)

-mode(compile).

main(_) ->
    Src = "src/arc/rt/names.gleam",
    Erl = "src/arc/rt/arc_rt_names_ffi.erl",
    Hrl = "src/arc/rt/arc_rt_names.hrl",
    Keys = "src/arc/rt/name_keys.gleam",
    {ok, Bin} = file:read_file(Src),
    Names = names(Bin),
    ok = check(Names),
    Count = length(Names),
    Print = fingerprint(Names),
    Numbered = lists:zip(Names, lists:seq(0, Count - 1)),
    ok = file:write_file(Erl, erl(Numbered, Count, Print)),
    ok = file:write_file(Hrl, hrl(Numbered, Count, Print)),
    ok = file:write_file(Keys, keys(Numbered, Print)),
    io:format("wrote ~ts, ~ts and ~ts (~b names)~n", [Erl, Hrl, Keys, Count]).

names(Bin) ->
    {Start, Len} = binary:match(Bin, <<"pub const fixed: List(String) = [">>),
    Rest = binary:part(Bin, Start + Len, byte_size(Bin) - Start - Len),
    [Body | _] = binary:split(Rest, <<"]">>),
    {ok, Re} = re:compile(<<"\"([^\"\\\\]*)\"">>),
    {match, Ms} = re:run(Body, Re, [global, {capture, all_but_first, binary}]),
    [M || [M] <- Ms].

%% tells a build's fixed list from another's, kept in snapshots and aot modules
fingerprint(Names) ->
    length(Names) * 134217728 + erlang:phash2(Names).

check(Names) ->
    Count = length(Names),
    Count = sets:size(sets:from_list(Names)),
    Macros = [macro(N) || N <- Names],
    Count = sets:size(sets:from_list(Macros)),
    false = lists:member("FIXED_COUNT", Macros),
    [] = [N || N <- Names, is_index(N)],
    Count = sets:size(sets:from_list(idents(Names))),
    ok.

is_index(<<"0">>) -> true;
is_index(<<C, _/binary>> = B) when C >= $1, C =< $9 ->
    lists:all(fun(D) -> D >= $0 andalso D =< $9 end, binary_to_list(B))
        andalso binary_to_integer(B) =< 4294967294;
is_index(_) -> false.

%% erl macro suffix: other characters spell as x and two hex digits
macro(Name) ->
    lists:flatten(
      [case C of
           _ when C >= $a, C =< $z; C >= $A, C =< $Z; C >= $0, C =< $9; C =:= $_ ->
               C;
           _ -> io_lib:format("x~2.16.0b", [C])
       end || <<C>> <= Name]).

%% gleam constant name: camel case to snake case (an upper case letter
%% after a lower case letter or digit starts a word), other characters spell
%% as x and two hex digits, a leading digit or _ gets an n prefix, then a _
%% suffix is appended until the name is unused and not a keyword; a name
%% that is already its own constant name claims it first, then earlier
%% names in the list win
idents(Names) ->
    Exact = [binary_to_list(N) || N <- Names, exact(N)],
    lists:reverse(
      lists:foldl(
        fun(N, Acc) ->
            case exact(N) of
                true -> [ident(N) | Acc];
                false -> [unused(ident(N), Exact ++ Acc) | Acc]
            end
        end, [], Names)).

exact(Name) ->
    S = binary_to_list(Name),
    ident(Name) =:= S andalso not lists:member(S, keywords())
        andalso S =/= "names_fingerprint".

ident(Name) ->
    S = snake(binary_to_list(Name), $_, []),
    case S of
        [C | _] when C >= $a, C =< $z -> S;
        _ -> "n" ++ S
    end.

snake([], _, Acc) -> lists:reverse(Acc);
snake([C | Rest], Prev, Acc) when C >= $A, C =< $Z ->
    case (Prev >= $a andalso Prev =< $z) orelse (Prev >= $0 andalso Prev =< $9) of
        true -> snake(Rest, C, [C + 32, $_ | Acc]);
        false -> snake(Rest, C, [C + 32 | Acc])
    end;
snake([C | Rest], _, Acc) when C >= $a, C =< $z; C >= $0, C =< $9; C =:= $_ ->
    snake(Rest, C, [C | Acc]);
snake([C | Rest], _, Acc) ->
    snake(Rest, C, lists:reverse(lists:flatten(io_lib:format("x~2.16.0b", [C]))) ++ Acc).

unused(S, Taken) ->
    case lists:member(S, Taken) orelse lists:member(S, keywords())
        orelse S =:= "names_fingerprint" of
        true -> unused(S ++ "_", Taken);
        false -> S
    end.

keywords() ->
    ["as", "assert", "auto", "case", "const", "delegate", "derive", "echo",
     "else", "fn", "if", "implement", "import", "let", "macro", "opaque",
     "panic", "pub", "test", "todo", "type", "use"].

header() ->
    "%% generated by scripts/gen_names.escript, do not edit\n".

lit(Name) ->
    io_lib:format("<<\"~ts\">>", [Name]).

erl(Numbered, Count, Print) ->
    [header(),
     "-module(arc_rt_names_ffi).\n",
     "-export([fixed_count/0, fingerprint/0, fixed_text/1, fixed_map/0]).\n\n",
     io_lib:format("fixed_count() -> ~b.\n\n", [Count]),
     io_lib:format("fingerprint() -> ~b.\n\n", [Print]),
     "fixed_text(N) -> element(N + 1, fixed_tuple()).\n\n",
     "fixed_map() ->\n    #{",
     lists:join(",\n      ", [[lit(N), " => ", integer_to_list(I)] || {N, I} <- Numbered]),
     "}.\n\n",
     "fixed_tuple() ->\n    {",
     lists:join(",\n     ", [lit(N) || {N, _} <- Numbered]),
     "}.\n"].

hrl(Numbered, Count, Print) ->
    [header(),
     "-ifndef(ARC_RT_NAMES_HRL).\n",
     "-define(ARC_RT_NAMES_HRL, true).\n\n",
     "-define(KEY_KIND_NAME, 0).\n",
     "-define(KEY_KIND_SYMBOL, 1).\n",
     "-define(KEY_KIND_PRIVATE, 2).\n",
     "-define(NAME_KEY(N), ((N) bsl 2)).\n",
     "-define(INDEX_KEY(I), (-(I) - 1)).\n\n",
     io_lib:format("-define(N_FIXED_COUNT, ~b).\n", [Count]),
     io_lib:format("-define(NAMES_FINGERPRINT, ~b).\n\n", [Print]),
     [io_lib:format("-define(N_~ts, ~b).\n", [macro(N), I]) || {N, I} <- Numbered],
     "\n",
     [io_lib:format("-define(K_~ts, ~b).\n", [macro(N), I * 4]) || {N, I} <- Numbered],
     "\n-endif.\n"].

keys(Numbered, Print) ->
    Idents = idents([N || {N, _} <- Numbered]),
    ["// generated by scripts/gen_names.escript, do not edit\n\n",
     io_lib:format("pub const names_fingerprint = ~b\n\n", [Print]),
     lists:join("\n", [io_lib:format("pub const ~ts = ~b\n", [Id, I * 4])
                       || {Id, {_, I}} <- lists:zip(Idents, Numbered)])].
