#!/usr/bin/env escript
%% -*- erlang -*-
%%
%% Writes src/arc/internal/arc_tz_links_ffi.erl: the IANA zone and link names
%% as Erlang literals, so name lookup and link resolution never depend on which
%% zoneinfo files the host happens to ship. Transition data still comes from
%% the host TZif files at run time.
%%
%% Input is a tzdata.zi (the compact zic source every tzdata build installs),
%% default /usr/share/zoneinfo/tzdata.zi.
%%
%% Run from the repository root:  escript scripts/gen_tz_links.escript [tzdata.zi]

-mode(compile).

main(Args) ->
    In = case Args of
        [Path] -> Path;
        [] -> "/usr/share/zoneinfo/tzdata.zi"
    end,
    Out = "src/arc/internal/arc_tz_links_ffi.erl",
    {ok, Bin} = file:read_file(In),
    Lines = binary:split(Bin, <<"\n">>, [global]),
    {Version, Zones0, Links0} = lists:foldl(fun line/2, {undefined, [], []}, Lines),
    Version =/= undefined orelse fail("no '# version' line in ~ts", [In]),
    Zones = lists:usort([Z || Z <- Zones0, keep(Z)]),
    ZoneSet = maps:from_list([{Z, true} || Z <- Zones]),
    Raw = maps:from_list([{L, T} || {T, L} <- Links0, keep(L)]),
    Links = maps:map(fun(L, T) -> resolve(L, T, Raw, ZoneSet, 8) end, Raw),
    Names = Zones ++ lists:sort(maps:keys(Links)),
    Lower = [{lower(N), N} || N <- Names],
    check_unique(Lower),
    [maps:is_key(L, ZoneSet) andalso fail("~ts is both zone and link", [L])
     || L <- maps:keys(Links)],
    Body =
        [header(In),
         "-module(arc_tz_links_ffi).\n"
         "-export([version/0, zones/0, links/0, names/0]).\n\n",
         "version() -> ", bin_lit(Version), ".\n\n",
         "zones() ->\n    [", join([bin_lit(Z) || Z <- Zones], ",\n     "),
         "].\n\n",
         "links() ->\n    #{", join([[bin_lit(L), " => ", bin_lit(T)]
                                  || {L, T} <- lists:sort(maps:to_list(Links))],
                                 ",\n      "),
         "}.\n\n",
         "names() ->\n    #{", join([[bin_lit(K), " => ", bin_lit(N)]
                                  || {K, N} <- lists:sort(Lower)],
                                 ",\n      "),
         "}.\n"],
    ok = file:write_file(Out, Body),
    io:format("wrote ~ts: tzdata ~ts, ~b zones, ~b links~n",
              [Out, Version, length(Zones), map_size(Links)]).

line(<<"# version ", V/binary>>, {undefined, Zs, Ls}) ->
    {string:trim(V), Zs, Ls};
line(<<"Z ", Rest/binary>>, {V, Zs, Ls}) ->
    [Name | _] = binary:split(Rest, <<" ">>),
    {V, [Name | Zs], Ls};
line(<<"L ", Rest/binary>>, {V, Zs, Ls}) ->
    [Target, Link | _] = binary:split(Rest, <<" ">>, [global]),
    {V, Zs, [{Target, Link} | Ls]};
line(_Other, Acc) -> Acc.

keep(<<"Factory">>) -> false;
keep(<<"posixrules">>) -> false;
keep(<<"posix/", _/binary>>) -> false;
keep(<<"right/", _/binary>>) -> false;
keep(<<"SystemV/", _/binary>>) -> false;
keep(_) -> true.

resolve(L, _T, _Raw, _Zones, 0) -> fail("link loop at ~ts", [L]);
resolve(L, T, Raw, Zones, N) ->
    case maps:is_key(T, Zones) of
        true -> T;
        false ->
            case maps:find(T, Raw) of
                {ok, Next} -> resolve(L, Next, Raw, Zones, N - 1);
                error -> fail("link ~ts targets unknown zone ~ts", [L, T])
            end
    end.

check_unique(Lower) ->
    Keys = [K || {K, _} <- Lower],
    length(Keys) =:= length(lists:usort(Keys))
        orelse fail("names collide case-insensitively", []).

lower(Bin) -> << <<(ascii_lower(C))>> || <<C>> <= Bin >>.

ascii_lower(C) when C >= $A, C =< $Z -> C + 32;
ascii_lower(C) -> C.

bin_lit(B) -> ["<<\"", binary_to_list(B), "\">>"].

join(Parts, Sep) -> lists:join(Sep, Parts).

header(In) ->
    ["%% generated by scripts/gen_tz_links.escript from ", In,
     ", do not edit\n"].

fail(Fmt, Args) ->
    io:format(standard_error, Fmt ++ "~n", Args),
    halt(1).
