#!/usr/bin/env escript
%% -*- erlang -*-
%% usage: escript scripts/gen_names.escript (from repo root)

-mode(compile).

main(_) ->
    Src = "src/arc/rt/names.gleam",
    Erl = "src/arc/rt/arc_rt_names_ffi.erl",
    Hrl = "src/arc/rt/arc_rt_names.hrl",
    {ok, Bin} = file:read_file(Src),
    Names = names(Bin),
    ok = check(Names),
    Count = length(Names),
    Numbered = lists:zip(Names, lists:seq(0, Count - 1)),
    ok = file:write_file(Erl, erl(Numbered, Count)),
    ok = file:write_file(Hrl, hrl(Numbered, Count)),
    io:format("wrote ~ts and ~ts (~b names)~n", [Erl, Hrl, Count]).

names(Bin) ->
    {Start, Len} = binary:match(Bin, <<"pub const fixed: List(String) = [">>),
    Rest = binary:part(Bin, Start + Len, byte_size(Bin) - Start - Len),
    [Body | _] = binary:split(Rest, <<"]">>),
    {ok, Re} = re:compile(<<"\"([^\"\\\\]*)\"">>),
    {match, Ms} = re:run(Body, Re, [global, {capture, all_but_first, binary}]),
    [M || [M] <- Ms].

check(Names) ->
    Count = length(Names),
    Count = sets:size(sets:from_list(Names)),
    Macros = [macro(N) || N <- Names],
    Count = sets:size(sets:from_list(Macros)),
    false = lists:member("FIXED_COUNT", Macros),
    [] = [N || N <- Names, is_index(N)],
    ok.

is_index(<<"0">>) -> true;
is_index(<<C, _/binary>> = B) when C >= $1, C =< $9 ->
    lists:all(fun(D) -> D >= $0 andalso D =< $9 end, binary_to_list(B))
        andalso binary_to_integer(B) =< 4294967294;
is_index(_) -> false.

macro(Name) ->
    [case C of
         _ when C >= $a, C =< $z; C >= $A, C =< $Z; C >= $0, C =< $9; C =:= $_ -> C;
         _ -> $_
     end || <<C>> <= Name].

header() ->
    "%% generated by scripts/gen_names.escript, do not edit\n".

lit(Name) ->
    io_lib:format("<<\"~ts\">>", [Name]).

erl(Numbered, Count) ->
    [header(),
     "-module(arc_rt_names_ffi).\n",
     "-export([fixed_count/0, fixed_number/1, fixed_text/1, fixed_map/0, fixed_tuple/0]).\n\n",
     io_lib:format("fixed_count() -> ~b.\n\n", [Count]),
     "fixed_number(Text) ->\n"
     "    case fixed_map() of\n"
     "        #{Text := N} -> N;\n"
     "        #{} -> none\n"
     "    end.\n\n",
     "fixed_text(N) -> element(N + 1, fixed_tuple()).\n\n",
     "fixed_map() ->\n    #{",
     lists:join(",\n      ", [[lit(N), " => ", integer_to_list(I)] || {N, I} <- Numbered]),
     "}.\n\n",
     "fixed_tuple() ->\n    {",
     lists:join(",\n     ", [lit(N) || {N, _} <- Numbered]),
     "}.\n"].

hrl(Numbered, Count) ->
    [header(),
     "-ifndef(ARC_RT_NAMES_HRL).\n",
     "-define(ARC_RT_NAMES_HRL, true).\n\n",
     "-define(KEY_KIND_NAME, 0).\n",
     "-define(KEY_KIND_SYMBOL, 1).\n",
     "-define(KEY_KIND_PRIVATE, 2).\n",
     "-define(NAME_KEY(N), ((N) bsl 2)).\n",
     "-define(INDEX_KEY(I), (-(I) - 1)).\n\n",
     io_lib:format("-define(N_FIXED_COUNT, ~b).\n\n", [Count]),
     [io_lib:format("-define(N_~ts, ~b).\n", [macro(N), I]) || {N, I} <- Numbered],
     "\n-endif.\n"].
