//// The `"js"` direct-host op table: every `CallHost("js", op, args)` the
//// emitter produces resolves here to a function in arc's runtime
//// (`arc@rt@*` / `arc_rt_*_ffi`) or an `erlang` BIF, with the calling
//// convention `emit_core` must use for it (`instance.OpKind`).

import carder/runtime/instance.{
  type DirectHost, DirectHost, HostOp, Mut, MutMiss, MutUnit, Pure, Read,
  ReadMiss,
}
import gleam/dict

pub fn table() -> DirectHost {
  let store = "arc@rt@store"
  let val = "arc@rt@val"
  let val_ffi = "arc_rt_val_ffi"
  let obj = "arc@rt@obj"
  let obj_ffi = "arc_rt_obj_ffi"
  let lang = "arc@rt@lang"
  let env = "arc@rt@env"
  let erl = "erlang"
  let ops = "arc@rt@ops"
  let ops_ffi = "arc_rt_ops_ffi"
  let call = "arc@rt@call"
  let call_ffi = "arc_rt_call_ffi"
  let class = "arc@rt@class"
  let async = "arc@rt@async"
  let gc = "arc@rt@gc"
  let builtins = "arc@rt@builtins"
  let math_ffi = "arc_rt_math_ffi"
  DirectHost(
    capability: "js",
    ops: dict.from_list([
      // Boxed bindings are `SBox` cells (GC-traceable), not raw-value cells.
      #("cell_new", HostOp(store, "t_var_new", Mut)),
      #("cell_get", HostOp(store, "t_var_get", Read)),
      #("cell_set", HostOp(store, "t_var_set", MutUnit)),
      #("pin_root", HostOp(store, "t_pin_root", MutUnit)),
      #("collect", HostOp(gc, "t_collect", MutUnit)),
      #("to_primitive", HostOp(val, "t_to_primitive", Mut)),
      #("to_number", HostOp(val, "t_to_number", Mut)),
      #("to_string", HostOp(val, "t_to_string", Mut)),
      #("to_property_key", HostOp(val, "t_to_property_key", Mut)),
      #("to_property_key_of", HostOp(val, "t_to_property_key_of", Mut)),
      #("to_property_key_fast", HostOp(val_ffi, "t_to_property_key_fast", Pure)),
      #("type_of", HostOp(val, "t_type_of", Mut)),
      #("to_object", HostOp(val, "t_to_object", Mut)),
      #("is_callable", HostOp(val, "t_is_callable", Mut)),
      #(
        "require_object_coercible",
        HostOp(val, "t_require_object_coercible", Mut),
      ),
      #("throw_type_error", HostOp(val, "t_throw_type_error", MutUnit)),
      #(
        "throw_reference_error",
        HostOp(val, "t_throw_reference_error", MutUnit),
      ),
      #("throw_syntax_error", HostOp(val, "t_throw_syntax_error", MutUnit)),
      #("truthy", HostOp(val_ffi, "to_boolean_i32", Pure)),
      #("is_nullish", HostOp(val, "is_nullish", Pure)),
      #("is_object", HostOp(val, "is_object", Pure)),
      #("float_lit", HostOp(erl, "binary_to_float", Pure)),
      #("empty_list", HostOp(val, "empty_list", Pure)),
      #("list_append_one", HostOp(val, "list_append_one", Pure)),
      #("string_concat", HostOp(val, "string_concat", Pure)),
      #("to_numeric", HostOp(val, "t_to_numeric", Mut)),
      #("tdz_check", HostOp(val, "t_tdz_check", MutUnit)),
      #("check_this", HostOp(val, "t_check_this", MutUnit)),
      #("new_object", HostOp(obj, "t_new_object_literal", Mut)),
      #("new_array", HostOp(obj, "t_new_array", Mut)),
      #("array_from_list", HostOp(obj, "t_new_array", Mut)),
      #("new_error", HostOp(lang, "t_new_error", Mut)),
      #("fn_new", HostOp(call, "t_new_function", Mut)),
      #("make_constructor", HostOp(call, "t_make_constructor", Mut)),
      #("new_arguments", HostOp(obj, "t_new_arguments", Mut)),
      #("get_prop", HostOp(obj, "t_get_prop_any", Mut)),
      #("get_prop_own_data", HostOp(obj_ffi, "t_get_prop_own_data", Read)),
      #("get_prop_ic", HostOp(obj_ffi, "t_get_prop_ic", ReadMiss)),
      #("get_prop_ic_miss", HostOp(obj_ffi, "t_get_prop_ic_miss", Mut)),
      #("get_prop_slow", HostOp(obj_ffi, "t_get_prop_slow", Mut)),
      #("get_prop_site", HostOp(obj_ffi, "t_get_prop_site", Mut)),
      #("erl_band", HostOp(erl, "band", Pure)),
      #("erl_bsr", HostOp(erl, "bsr", Pure)),
      #("erl_bsl", HostOp(erl, "bsl", Pure)),
      #("set_prop", HostOp(obj, "t_set_prop_any", Mut)),
      #("set_prop_strict", HostOp(obj, "t_set_prop_strict", Mut)),
      #("set_prop_own_data", HostOp(obj_ffi, "t_set_prop_own_data", MutMiss)),
      #("set_prop_named", HostOp(obj_ffi, "t_set_prop_named", MutUnit)),
      #("get_elem_fast", HostOp(obj_ffi, "t_get_elem_fast", Read)),
      #("set_elem_fast", HostOp(obj_ffi, "t_set_elem_fast", MutMiss)),
      #("define_prop", HostOp(obj, "t_create_data_prop", Mut)),
      #("has_prop", HostOp(obj, "t_has_prop", Mut)),
      #("delete_prop", HostOp(obj, "t_delete_prop", Mut)),
      #("delete_prop_strict", HostOp(obj, "t_delete_prop_strict", Mut)),
      #("own_keys", HostOp(obj, "t_own_keys", Mut)),
      #("copy_data_props", HostOp(lang, "t_copy_data_props", Mut)),
      #("object_rest", HostOp(lang, "t_object_rest", Mut)),
      #("get_iterator", HostOp(lang, "t_get_iterator", Mut)),
      #("iter_next", HostOp(lang, "t_iter_next", Mut)),
      #("iter_close", HostOp(lang, "t_iter_close", MutUnit)),
      #("iter_rest", HostOp(lang, "t_iter_rest", Mut)),
      #("spread_into_list", HostOp(lang, "t_spread_into_list", Mut)),
      #("async_iter_next", HostOp(lang, "t_async_iter_next", Mut)),
      #("regexp_new", HostOp(lang, "t_regexp_new", Mut)),
      #("get_template_object", HostOp(lang, "t_get_template_object", Mut)),
      #("for_in_keys", HostOp(obj, "t_for_in_keys", Mut)),
      #("global_get", HostOp(obj_ffi, "t_global_get", Mut)),
      #("global_get_fast", HostOp(obj_ffi, "t_global_get_fast", ReadMiss)),
      #("global_this", HostOp(obj, "t_global_this", Read)),
      #("global_set", HostOp(obj, "t_global_set", MutUnit)),
      #("global_set_strict", HostOp(obj, "t_global_set_strict", MutUnit)),
      #("global_typeof", HostOp(obj, "t_global_typeof", Mut)),
      #("global_delete", HostOp(lang, "t_global_delete", Mut)),
      #(
        "declare_global_var",
        HostOp(env, "t_create_global_var_binding", MutUnit),
      ),
      #("declare_global_fn", HostOp(env, "t_create_global_fn_binding", MutUnit)),
      #("set_proto", HostOp(obj, "t_set_proto", Mut)),
      #("num_add", HostOp(ops_ffi, "add", Pure)),
      #("num_sub", HostOp(ops_ffi, "sub", Pure)),
      #("num_mul", HostOp(ops_ffi, "mul", Pure)),
      #("num_div", HostOp(ops_ffi, "div", Pure)),
      #("num_mod", HostOp(ops_ffi, "mod", Pure)),
      #("num_neg", HostOp(ops_ffi, "neg", Pure)),
      #("add_prim", HostOp(ops_ffi, "add", Pure)),
      #("add_any", HostOp(ops_ffi, "t_add", Mut)),
      #("sub_any", HostOp(ops_ffi, "t_sub", Mut)),
      #("mul_any", HostOp(ops_ffi, "t_mul", Mut)),
      #("add", HostOp(ops, "t_add", Mut)),
      #("sub", HostOp(ops, "t_sub", Mut)),
      #("mul", HostOp(ops, "t_mul", Mut)),
      #("div", HostOp(ops_ffi, "t_div", Mut)),
      #("mod", HostOp(ops_ffi, "t_mod", Mut)),
      #("pow", HostOp(ops, "t_pow", Mut)),
      #("neg", HostOp(ops_ffi, "t_neg", Mut)),
      #("plus", HostOp(ops, "t_plus", Mut)),
      #("bitnot", HostOp(ops, "t_bitnot", Mut)),
      #("bitand", HostOp(ops, "t_bitand", Mut)),
      #("bitor", HostOp(ops, "t_bitor", Mut)),
      #("bitxor", HostOp(ops, "t_bitxor", Mut)),
      #("shl", HostOp(ops, "t_shl", Mut)),
      #("shr", HostOp(ops, "t_shr", Mut)),
      #("ushr", HostOp(ops, "t_ushr", Mut)),
      #("lt", HostOp(ops, "t_lt", Mut)),
      #("le", HostOp(ops, "t_le", Mut)),
      #("gt", HostOp(ops, "t_gt", Mut)),
      #("ge", HostOp(ops, "t_ge", Mut)),
      #("eq", HostOp(ops, "t_eq", Mut)),
      #("eq_fast", HostOp(ops_ffi, "t_eq_fast", Pure)),
      #("nul_eq", HostOp(ops_ffi, "nul_eq", Pure)),
      #("bitand_fast", HostOp(ops_ffi, "t_bitand_fast", Pure)),
      #("bitor_fast", HostOp(ops_ffi, "t_bitor_fast", Pure)),
      #("bitxor_fast", HostOp(ops_ffi, "t_bitxor_fast", Pure)),
      #("shl_fast", HostOp(ops_ffi, "t_shl_fast", Pure)),
      #("shr_fast", HostOp(ops_ffi, "t_shr_fast", Pure)),
      #("ushr_fast", HostOp(ops_ffi, "t_ushr_fast", Pure)),
      #("bitnot_fast", HostOp(ops_ffi, "t_bitnot_fast", Pure)),
      #("strict_eq", HostOp(ops, "strict_eq", Pure)),
      #("strict_eq_i32", HostOp(ops_ffi, "strict_eq_i32", Pure)),
      #("op_in", HostOp(ops, "t_in", Mut)),
      #("instance_of", HostOp(ops, "t_instance_of", Mut)),
      #("instanceof_fast", HostOp(obj_ffi, "t_instanceof_fast", Read)),
      #("call", HostOp(call, "t_call_checked", Mut)),
      #("call_fast", HostOp(call_ffi, "t_call_fast", Mut)),
      #("call_fast0", HostOp(call_ffi, "t_call_fast0", Mut)),
      #("call_fast1", HostOp(call_ffi, "t_call_fast1", Mut)),
      #("call_fast2", HostOp(call_ffi, "t_call_fast2", Mut)),
      #("call_fast3", HostOp(call_ffi, "t_call_fast3", Mut)),
      #("call_method_mono", HostOp(call_ffi, "t_call_method_mono", Mut)),
      #("call_method_ic", HostOp(call_ffi, "t_call_method_ic", Mut)),
      #("call_method_ic0", HostOp(call_ffi, "t_call_method_ic0", Mut)),
      #("call_method_ic1", HostOp(call_ffi, "t_call_method_ic1", Mut)),
      #("call_method_ic2", HostOp(call_ffi, "t_call_method_ic2", Mut)),
      #("call_method_ic3", HostOp(call_ffi, "t_call_method_ic3", Mut)),
      #("construct", HostOp(call, "t_construct", Mut)),
      #("new_simple", HostOp(call_ffi, "t_new_simple", Mut)),
      #("kfn_code", HostOp(call_ffi, "t_kfn_code", Read)),
      #("new_private_name", HostOp(class, "t_new_private_name", Mut)),
      #("class_setup", HostOp(class, "t_class_setup", Mut)),
      #("define_method", HostOp(class, "t_define_method", MutUnit)),
      #("define_private", HostOp(class, "t_define_private", MutUnit)),
      #("set_fields_init", HostOp(class, "t_set_fields_init", MutUnit)),
      #("private_get", HostOp(class, "t_private_get", Mut)),
      #("private_set", HostOp(class, "t_private_set", Mut)),
      #("private_define", HostOp(class, "t_private_define", MutUnit)),
      #("private_in", HostOp(class, "t_private_in", Read)),
      #("fn_home_object", HostOp(class, "t_fn_home_object", Read)),
      #("is_constructor", HostOp(class, "t_is_constructor", Read)),
      #("super_get", HostOp(class, "t_super_get", Mut)),
      #("super_set", HostOp(class, "t_super_set", Mut)),
      #("super_call", HostOp(class, "t_super_call", Mut)),
      #("make_method", HostOp(class, "t_make_method", MutUnit)),
      #("async_start", HostOp(async, "t_async_start", Mut)),
      #("async_reject", HostOp(async, "t_async_reject", Mut)),
      #("gen_start", HostOp(async, "t_gen_start", Mut)),
      #("asyncgen_start", HostOp(async, "t_asyncgen_start", Mut)),
      #("await", HostOp(async, "t_await", MutUnit)),
      #("init_realm", HostOp(builtins, "init_realm", MutUnit)),
      #("math_sqrt", HostOp(math_ffi, "t_math_sqrt", Pure)),
      #("math_floor", HostOp(math_ffi, "t_math_floor", Pure)),
      #("math_abs", HostOp(math_ffi, "t_math_abs", Pure)),
      #("math_pow", HostOp(math_ffi, "t_math_pow", Pure)),
      #("math_min", HostOp(math_ffi, "t_math_min", Pure)),
      #("math_max", HostOp(math_ffi, "t_math_max", Pure)),
    ]),
  )
}
