import carder/runtime/instance.{
  type DirectHost, DirectHost, HostOp, Mut, MutMiss, MutUnit, Pure, Read,
  ReadMiss,
}
import gleam/dict

pub fn table() -> DirectHost {
  let store = "arc@rt@store"
  let val = "arc@rt@val"
  let val_ffi = "arc_rt_val_ffi"
  let js_string_ffi = "arc_rt_js_string_ffi"
  let obj = "arc@rt@obj"
  let obj_ffi = "arc_rt_obj_ffi"
  let obj_ic_ffi = "arc_rt_obj_ic_ffi"
  let lang = "arc@rt@lang"
  let env = "arc@rt@env"
  let erl = "erlang"
  let ops = "arc@rt@ops"
  let ops_ffi = "arc_rt_ops_ffi"
  let call = "arc@rt@call"
  let call_ffi = "arc_rt_call_ffi"
  let call_ic_ffi = "arc_rt_call_ic_ffi"
  let class = "arc@rt@class"
  let async = "arc@rt@async"
  let gc = "arc@rt@gc"
  let builtins = "arc@rt@builtins"
  let math_ffi = "arc_rt_math_ffi"
  DirectHost(
    capability: "js",
    ops: dict.from_list([
      #("box_new", HostOp(store, "t_box_new", Mut)),
      #("box_get", HostOp(store, "t_box_get", Read)),
      #("box_set", HostOp(store, "t_box_set", MutUnit)),
      #("pin_root", HostOp(store, "t_pin_root", MutUnit)),
      #("collect", HostOp(gc, "t_collect", MutUnit)),
      #("to_primitive", HostOp(val, "t_to_primitive", Mut)),
      #("to_number", HostOp(val, "t_to_number", Mut)),
      #("to_string", HostOp(val, "t_to_string", Mut)),
      #("to_property_key", HostOp(val, "t_to_property_key", Mut)),
      #("to_property_key_of", HostOp(val, "t_to_property_key_of", Mut)),
      #("property_key_of", HostOp(val_ffi, "property_key_of", Pure)),
      #("type_of", HostOp(val, "type_of", Read)),
      #("to_object", HostOp(val, "t_to_object", Mut)),
      #("is_callable", HostOp(val, "is_callable", Read)),
      #(
        "require_object_coercible",
        HostOp(val, "t_require_object_coercible", Mut),
      ),
      #("throw_type_error", HostOp(val, "t_throw_type_error", MutUnit)),
      #(
        "throw_reference_error",
        HostOp(val, "t_throw_reference_error", MutUnit),
      ),
      #("throw_syntax_error", HostOp(val, "t_throw_syntax_error", MutUnit)),
      #("to_boolean_i32", HostOp(val_ffi, "to_boolean_i32", Pure)),
      #("is_nullish", HostOp(val_ffi, "is_nullish", Pure)),
      #("is_object", HostOp(val, "is_object", Pure)),
      #("binary_to_float", HostOp(erl, "binary_to_float", Pure)),
      #("empty_list", HostOp(val, "empty_list", Pure)),
      #("list_append_one", HostOp(val, "list_append_one", Pure)),
      #("concat_loose", HostOp(js_string_ffi, "concat_loose", Pure)),
      #("to_numeric", HostOp(val, "t_to_numeric", Mut)),
      #("tdz_check", HostOp(val, "t_tdz_check", MutUnit)),
      #("check_this", HostOp(val, "t_check_this", MutUnit)),
      #("new_object_literal", HostOp(obj, "t_new_object_literal", Mut)),
      #("new_object_props", HostOp(obj_ic_ffi, "t_new_object_props", Mut)),
      #("new_array", HostOp(obj, "t_new_array", Mut)),
      #("array_lit", HostOp(obj_ffi, "t_array_lit", Mut)),
      #("array_lit_packed", HostOp(obj_ffi, "t_array_lit_packed", Mut)),
      #("new_type_error", HostOp(lang, "t_new_type_error", Mut)),
      #("new_function", HostOp(call, "t_new_function", Mut)),
      #("new_arguments", HostOp(obj, "t_new_arguments", Mut)),
      #("get_prop_untyped_key", HostOp(obj, "t_get_prop_untyped_key", Mut)),
      #("get_prop_own_data", HostOp(obj_ffi, "t_get_prop_own_data", Read)),
      #(
        "get_named_ic_shaped",
        HostOp(obj_ic_ffi, "t_get_named_ic_shaped", ReadMiss),
      ),
      #("get_named_ic_fill", HostOp(obj_ffi, "t_get_named_ic_fill", Mut)),
      #("get_named", HostOp(obj_ffi, "t_get_named", Mut)),
      #("get_named_site", HostOp(obj_ffi, "t_get_named_site", Mut)),
      #("get_named_ic", HostOp(obj_ic_ffi, "t_get_named_ic", ReadMiss)),
      #("band", HostOp(erl, "band", Pure)),
      #("bsr", HostOp(erl, "bsr", Pure)),
      #("bsl", HostOp(erl, "bsl", Pure)),
      #("rem", HostOp(erl, "rem", Pure)),
      #("set_prop_untyped_key", HostOp(obj, "t_set_prop_untyped_key", Mut)),
      #("set_prop_strict", HostOp(obj, "t_set_prop_strict", Mut)),
      #("set_prop_own_data", HostOp(obj_ffi, "t_set_prop_own_data", MutMiss)),
      #("set_named_ic", HostOp(obj_ic_ffi, "t_set_named_ic", MutUnit)),
      #("set_named_many", HostOp(obj_ic_ffi, "t_set_named_many", MutUnit)),
      #("set_named_init_ic", HostOp(obj_ic_ffi, "t_set_named_init_ic", MutUnit)),
      #("get_elem", HostOp(obj_ffi, "t_get_elem", Read)),
      #("set_elem", HostOp(obj_ffi, "t_set_elem", MutMiss)),
      #("create_data_prop", HostOp(obj, "t_create_data_prop", Mut)),
      #("has_prop", HostOp(obj, "t_has_prop", Mut)),
      #("delete_prop", HostOp(obj, "t_delete_prop", Mut)),
      #("delete_prop_strict", HostOp(obj, "t_delete_prop_strict", Mut)),
      #("own_keys", HostOp(obj, "t_own_keys", Mut)),
      #("copy_data_props", HostOp(lang, "t_copy_data_props", Mut)),
      #("object_rest", HostOp(lang, "t_object_rest", Mut)),
      #("get_iterator", HostOp(lang, "t_get_iterator", Mut)),
      #("iter_next", HostOp(lang, "t_iter_next", Mut)),
      #("iter_close", HostOp(lang, "t_iter_close", MutUnit)),
      #("iter_rest", HostOp(lang, "t_iter_rest", Mut)),
      #("spread_into_list", HostOp(lang, "t_spread_into_list", Mut)),
      #("async_iter_next", HostOp(lang, "t_async_iter_next", Mut)),
      #("regexp_new", HostOp(lang, "t_regexp_new", Mut)),
      #("get_template_object", HostOp(lang, "t_get_template_object", Mut)),
      #("for_in_keys", HostOp(obj, "t_for_in_keys", Mut)),
      #("global_get", HostOp(obj_ffi, "t_global_get", Mut)),
      #("global_get_ic", HostOp(obj_ic_ffi, "t_global_get_ic", ReadMiss)),
      #("global_get_ic_fill", HostOp(obj_ic_ffi, "t_global_get_ic_fill", Mut)),
      #("global_this", HostOp(obj, "t_global_this", Read)),
      #("global_set", HostOp(obj, "t_global_set", MutUnit)),
      #("global_set_strict", HostOp(obj, "t_global_set_strict", MutUnit)),
      #("global_typeof", HostOp(obj, "t_global_typeof", Mut)),
      #("global_delete", HostOp(lang, "t_global_delete", Mut)),
      #(
        "create_global_var_binding",
        HostOp(env, "t_create_global_var_binding", MutUnit),
      ),
      #(
        "create_global_fn_binding",
        HostOp(env, "t_create_global_fn_binding", MutUnit),
      ),
      #("set_proto", HostOp(obj, "t_set_proto", Mut)),
      #("add", HostOp(ops_ffi, "add", Pure)),
      #("sub", HostOp(ops_ffi, "sub", Pure)),
      #("mul", HostOp(ops_ffi, "mul", Pure)),
      #("div", HostOp(ops_ffi, "div", Pure)),
      #("mod", HostOp(ops_ffi, "mod", Pure)),
      #("neg", HostOp(ops_ffi, "neg", Pure)),
      #("add_general", HostOp(ops_ffi, "t_add", Mut)),
      #("sub_general", HostOp(ops_ffi, "t_sub", Mut)),
      #("mul_general", HostOp(ops_ffi, "t_mul", Mut)),
      #("div_general", HostOp(ops_ffi, "t_div", Mut)),
      #("mod_general", HostOp(ops_ffi, "t_mod", Mut)),
      #("pow", HostOp(ops, "t_pow", Mut)),
      #("neg_general", HostOp(ops_ffi, "t_neg", Mut)),
      #("plus", HostOp(ops, "t_plus", Mut)),
      #("bitnot_general", HostOp(ops, "t_bitnot", Mut)),
      #("bitand_general", HostOp(ops, "t_bitand", Mut)),
      #("bitor_general", HostOp(ops, "t_bitor", Mut)),
      #("bitxor_general", HostOp(ops, "t_bitxor", Mut)),
      #("shl_general", HostOp(ops, "t_shl", Mut)),
      #("shr_general", HostOp(ops, "t_shr", Mut)),
      #("ushr_general", HostOp(ops, "t_ushr", Mut)),
      #("lt", HostOp(ops, "t_lt", Mut)),
      #("le", HostOp(ops, "t_le", Mut)),
      #("gt", HostOp(ops, "t_gt", Mut)),
      #("ge", HostOp(ops, "t_ge", Mut)),
      #("eq", HostOp(ops, "t_eq", Mut)),
      #("eq_i32", HostOp(ops_ffi, "eq_i32", Pure)),
      #("is_nullish_i32", HostOp(val_ffi, "is_nullish_i32", Pure)),
      #("bitand", HostOp(ops_ffi, "bitand", Pure)),
      #("bitor", HostOp(ops_ffi, "bitor", Pure)),
      #("bitxor", HostOp(ops_ffi, "bitxor", Pure)),
      #("shl", HostOp(ops_ffi, "shl", Pure)),
      #("shr", HostOp(ops_ffi, "shr", Pure)),
      #("ushr", HostOp(ops_ffi, "ushr", Pure)),
      #("bitnot", HostOp(ops_ffi, "bitnot", Pure)),
      #("strict_eq", HostOp(ops, "strict_eq", Pure)),
      #("strict_eq_i32", HostOp(ops_ffi, "strict_eq_i32", Pure)),
      #("in", HostOp(ops, "t_in", Mut)),
      #(
        "instanceof_i32_general",
        HostOp(obj_ffi, "t_instanceof_i32_general", Mut),
      ),
      #("instanceof_i32", HostOp(obj_ffi, "t_instanceof_i32", Read)),
      #("call", HostOp(call, "t_call", Mut)),
      #("call_by_kind", HostOp(call_ic_ffi, "t_call_by_kind", Mut)),
      #("call_by_kind0", HostOp(call_ic_ffi, "t_call_by_kind0", Mut)),
      #("call_by_kind1", HostOp(call_ic_ffi, "t_call_by_kind1", Mut)),
      #("call_by_kind2", HostOp(call_ic_ffi, "t_call_by_kind2", Mut)),
      #("call_by_kind3", HostOp(call_ic_ffi, "t_call_by_kind3", Mut)),
      #("call_method_mono", HostOp(call_ic_ffi, "t_call_method_mono", Mut)),
      #("call_method_ic", HostOp(call_ic_ffi, "t_call_method_ic", Mut)),
      #("call_method_ic0", HostOp(call_ic_ffi, "t_call_method_ic0", Mut)),
      #("call_method_ic1", HostOp(call_ic_ffi, "t_call_method_ic1", Mut)),
      #("call_method_ic2", HostOp(call_ic_ffi, "t_call_method_ic2", Mut)),
      #("call_method_ic3", HostOp(call_ic_ffi, "t_call_method_ic3", Mut)),
      #("construct", HostOp(call, "t_construct", Mut)),
      #("new_direct", HostOp(call_ic_ffi, "t_new_direct", Mut)),
      #("direct_callee", HostOp(call_ffi, "t_direct_callee", Read)),
      #("new_private_name", HostOp(class, "t_new_private_name", Mut)),
      #("class_setup", HostOp(class, "t_setup", Mut)),
      #("define_method", HostOp(class, "t_define_method", MutUnit)),
      #("define_private", HostOp(class, "t_define_private", MutUnit)),
      #("set_fields_init", HostOp(class, "t_set_fields_init", MutUnit)),
      #("private_get", HostOp(class, "t_private_get", Mut)),
      #("private_set", HostOp(class, "t_private_set", Mut)),
      #("private_define", HostOp(class, "t_private_define", MutUnit)),
      #("private_in", HostOp(class, "t_private_in", Read)),
      #("fn_home_object", HostOp(class, "t_fn_home_object", Read)),
      #("is_constructor", HostOp(call, "is_constructor", Read)),
      #("super_get", HostOp(class, "t_super_get", Mut)),
      #("super_set", HostOp(class, "t_super_set", Mut)),
      #("super_call", HostOp(class, "t_super_call", Mut)),
      #("make_method", HostOp(class, "t_make_method", MutUnit)),
      #("async_start", HostOp(async, "t_start", Mut)),
      #("async_reject", HostOp(async, "t_reject", Mut)),
      #("gen_start", HostOp(async, "t_gen_start", Mut)),
      #("asyncgen_start", HostOp(async, "t_asyncgen_start", Mut)),
      #("await", HostOp(async, "t_await", MutUnit)),
      #("init_realm", HostOp(builtins, "init_realm", MutUnit)),
      #("math_sqrt", HostOp(math_ffi, "t_math_sqrt", Pure)),
      #("math_floor", HostOp(math_ffi, "t_math_floor", Pure)),
      #("math_abs", HostOp(math_ffi, "t_math_abs", Pure)),
      #("math_pow", HostOp(math_ffi, "t_math_pow", Pure)),
      #("math_min", HostOp(math_ffi, "t_math_min", Pure)),
      #("math_max", HostOp(math_ffi, "t_math_max", Pure)),
    ]),
  )
}
