import carder/runtime/instance.{
  type DirectHost, DirectHost, HostOp, Mut, MutMiss, MutUnit, Pure, Read,
  ReadMiss,
}
import gleam/dict

pub fn table() -> DirectHost {
  let store = "arc@rt@store"
  let val = "arc@rt@val"
  let val_ffi = "arc_rt_val_ffi"
  let js_string_ffi = "arc_rt_js_string_ffi"
  let obj = "arc@rt@obj"
  let obj_ffi = "arc_rt_obj_ffi"
  let obj_ic_ffi = "arc_rt_obj_ic_ffi"
  let lang = "arc@rt@lang"
  let env = "arc@rt@env"
  let erl = "erlang"
  let ops = "arc@rt@ops"
  let ops_ffi = "arc_rt_ops_ffi"
  let call = "arc@rt@call"
  let call_ffi = "arc_rt_call_ffi"
  let call_ic_ffi = "arc_rt_call_ic_ffi"
  let class = "arc@rt@class"
  let async = "arc@rt@async"
  let regexp = "arc@rt@builtins@regexp"
  let math_ffi = "arc_rt_math_ffi"
  DirectHost(
    capability: "js",
    ops: dict.from_list([
      #("box_new", HostOp(store, "box_new", Mut)),
      #("box_get", HostOp(store, "box_get", Read)),
      #("box_set", HostOp(store, "box_set", MutUnit)),
      #("to_string", HostOp(val, "to_string", Mut)),
      #("to_property_key", HostOp(val, "to_property_key", Mut)),
      #("to_property_key_of", HostOp(val, "to_property_key_of", Mut)),
      #("property_key_of", HostOp(val_ffi, "property_key_of", Pure)),
      #("type_of", HostOp(val, "type_of", Read)),
      #(
        "require_object_coercible",
        HostOp(val, "require_object_coercible", Read),
      ),
      #("throw_type_error", HostOp(val, "throw_type_error", MutUnit)),
      #("throw_reference_error", HostOp(val, "throw_reference_error", MutUnit)),
      #("throw_syntax_error", HostOp(val, "throw_syntax_error", MutUnit)),
      #("to_boolean_i32", HostOp(val_ffi, "to_boolean_i32", Pure)),
      #("is_nullish", HostOp(val_ffi, "is_nullish", Pure)),
      #("is_object", HostOp(val, "is_object", Pure)),
      #("binary_to_float", HostOp(erl, "binary_to_float", Pure)),
      #("empty_list", HostOp(val, "empty_list", Pure)),
      #("list_append_one", HostOp(val, "list_append_one", Pure)),
      #("concat_loose", HostOp(js_string_ffi, "concat_loose", Pure)),
      #("to_numeric", HostOp(val, "to_numeric", Mut)),
      #("tdz_check", HostOp(val, "tdz_check", MutUnit)),
      #("check_this", HostOp(val, "check_this", MutUnit)),
      #("new_object_literal", HostOp(obj, "new_object_literal", Mut)),
      #("new_object_props", HostOp(obj_ic_ffi, "new_object_props", Mut)),
      #("new_array", HostOp(obj, "new_array", Mut)),
      #("array_lit", HostOp(obj_ffi, "array_lit", Mut)),
      #("array_lit_packed", HostOp(obj_ffi, "array_lit_packed", Mut)),
      #("new_error", HostOp(val, "new_error", Mut)),
      #("new_closure", HostOp(call, "new_closure", Mut)),
      #("new_arguments", HostOp(obj, "new_arguments", Mut)),
      #("get_prop_untyped_key", HostOp(obj, "get_prop_untyped_key", Mut)),
      #(
        "get_named_ic_shaped",
        HostOp(obj_ic_ffi, "get_named_ic_shaped", ReadMiss),
      ),
      #("get_named", HostOp(obj_ffi, "get_named", Mut)),
      #("get_named_site", HostOp(obj_ffi, "get_named_site", Mut)),
      #("get_named_ic", HostOp(obj_ic_ffi, "get_named_ic", ReadMiss)),
      #("band", HostOp(erl, "band", Pure)),
      #("bsr", HostOp(erl, "bsr", Pure)),
      #("bsl", HostOp(erl, "bsl", Pure)),
      #("rem", HostOp(erl, "rem", Pure)),
      #("set_prop_untyped_key", HostOp(obj, "set_prop_untyped_key", Mut)),
      #(
        "set_prop_strict_untyped_key",
        HostOp(obj, "set_prop_strict_untyped_key", Mut),
      ),
      #("set_named_ic", HostOp(obj_ic_ffi, "set_named_ic", MutUnit)),
      #("set_named_init_ic", HostOp(obj_ic_ffi, "set_named_init_ic", MutUnit)),
      #("get_elem", HostOp(obj_ffi, "get_elem", Read)),
      #("set_elem", HostOp(obj_ffi, "set_elem", MutMiss)),
      #("create_data_prop", HostOp(obj, "create_data_prop", Mut)),
      #("delete_prop", HostOp(obj, "delete_prop", Mut)),
      #("delete_prop_strict", HostOp(obj, "delete_prop_strict", Mut)),
      #("copy_data_props", HostOp(lang, "copy_data_props", Mut)),
      #("object_rest", HostOp(lang, "object_rest", Mut)),
      #("get_iterator", HostOp(lang, "get_iterator", Mut)),
      #("iter_next", HostOp(lang, "iter_next", Mut)),
      #("iter_close", HostOp(lang, "iter_close", MutUnit)),
      #("iter_rest", HostOp(lang, "iter_rest", Mut)),
      #("spread_into_list", HostOp(lang, "spread_into_list", Mut)),
      #("async_iter_next", HostOp(lang, "async_iter_next", Mut)),
      #("regexp_new", HostOp(regexp, "create_literal", Mut)),
      #("get_template_object", HostOp(lang, "get_template_object", Mut)),
      #("for_in_keys", HostOp(obj, "for_in_keys", Mut)),
      #("global_get", HostOp(obj_ffi, "global_get", Mut)),
      #("global_get_ic", HostOp(obj_ic_ffi, "global_get_ic", ReadMiss)),
      #("global_get_ic_fill", HostOp(obj_ic_ffi, "global_get_ic_fill", Mut)),
      #("global_this", HostOp(lang, "global_this", Read)),
      #("global_set", HostOp(lang, "global_set", MutUnit)),
      #("global_set_strict", HostOp(lang, "global_set_strict", MutUnit)),
      #("global_typeof", HostOp(lang, "global_typeof", Mut)),
      #("global_delete", HostOp(lang, "global_delete", Mut)),
      #(
        "create_global_var_binding",
        HostOp(env, "create_global_var_binding", MutUnit),
      ),
      #(
        "create_global_fn_binding",
        HostOp(env, "create_global_fn_binding", MutUnit),
      ),
      #("set_proto", HostOp(obj, "set_proto", Mut)),
      #("add", HostOp(ops_ffi, "add", Pure)),
      #("sub", HostOp(ops_ffi, "sub", Pure)),
      #("mul", HostOp(ops_ffi, "mul", Pure)),
      #("div", HostOp(ops_ffi, "div", Pure)),
      #("mod", HostOp(ops_ffi, "mod", Pure)),
      #("neg", HostOp(ops_ffi, "neg", Pure)),
      #("add_general", HostOp(ops_ffi, "add_general", Mut)),
      #("sub_general", HostOp(ops_ffi, "sub_general", Mut)),
      #("mul_general", HostOp(ops_ffi, "mul_general", Mut)),
      #("div_general", HostOp(ops_ffi, "div_general", Mut)),
      #("mod_general", HostOp(ops_ffi, "mod_general", Mut)),
      #("pow", HostOp(ops, "pow", Mut)),
      #("neg_general", HostOp(ops_ffi, "neg_general", Mut)),
      #("plus", HostOp(ops, "plus", Mut)),
      #("bitnot_general", HostOp(ops, "bitnot_general", Mut)),
      #("bitand_general", HostOp(ops, "bitand_general", Mut)),
      #("bitor_general", HostOp(ops, "bitor_general", Mut)),
      #("bitxor_general", HostOp(ops, "bitxor_general", Mut)),
      #("shl_general", HostOp(ops, "shl_general", Mut)),
      #("shr_general", HostOp(ops, "shr_general", Mut)),
      #("ushr_general", HostOp(ops, "ushr_general", Mut)),
      #("lt_i32", HostOp(ops, "lt_i32", Mut)),
      #("le_i32", HostOp(ops, "le_i32", Mut)),
      #("gt_i32", HostOp(ops, "gt_i32", Mut)),
      #("ge_i32", HostOp(ops, "ge_i32", Mut)),
      #("eq_i32_general", HostOp(ops, "eq_i32_general", Mut)),
      #("eq_i32", HostOp(ops_ffi, "eq_i32", Pure)),
      #("bitand", HostOp(ops_ffi, "bitand", Pure)),
      #("bitor", HostOp(ops_ffi, "bitor", Pure)),
      #("bitxor", HostOp(ops_ffi, "bitxor", Pure)),
      #("shl", HostOp(ops_ffi, "shl", Pure)),
      #("shr", HostOp(ops_ffi, "shr", Pure)),
      #("ushr", HostOp(ops_ffi, "ushr", Pure)),
      #("bitnot", HostOp(ops_ffi, "bitnot", Pure)),
      #("strict_eq", HostOp(val_ffi, "strict_eq", Pure)),
      #("strict_eq_i32", HostOp(ops_ffi, "strict_eq_i32", Pure)),
      #("in", HostOp(ops, "in", Mut)),
      #(
        "instanceof_i32_general",
        HostOp(obj_ffi, "instanceof_i32_general", Mut),
      ),
      #("instanceof_i32", HostOp(obj_ffi, "instanceof_i32", Read)),
      #("call", HostOp(call, "call", Mut)),
      #("call_by_kind", HostOp(call_ic_ffi, "call_by_kind", Mut)),
      #("call_by_kind0", HostOp(call_ic_ffi, "call_by_kind0", Mut)),
      #("call_by_kind1", HostOp(call_ic_ffi, "call_by_kind1", Mut)),
      #("call_by_kind2", HostOp(call_ic_ffi, "call_by_kind2", Mut)),
      #("call_by_kind3", HostOp(call_ic_ffi, "call_by_kind3", Mut)),
      #("call_method_ic", HostOp(call_ic_ffi, "call_method_ic", Mut)),
      #("call_method_ic0", HostOp(call_ic_ffi, "call_method_ic0", Mut)),
      #("call_method_ic1", HostOp(call_ic_ffi, "call_method_ic1", Mut)),
      #("call_method_ic2", HostOp(call_ic_ffi, "call_method_ic2", Mut)),
      #("call_method_ic3", HostOp(call_ic_ffi, "call_method_ic3", Mut)),
      #("construct", HostOp(call, "construct", Mut)),
      #("new_direct", HostOp(call_ic_ffi, "new_direct", Mut)),
      #("direct_callee", HostOp(call_ffi, "direct_callee", Read)),
      #("new_private_name", HostOp(class, "new_private_name", Mut)),
      #("setup", HostOp(class, "setup", Mut)),
      #("define_method", HostOp(class, "define_method", MutUnit)),
      #("private_method_add", HostOp(class, "private_method_add", MutUnit)),
      #("set_fields_init", HostOp(class, "set_fields_init", MutUnit)),
      #("private_get", HostOp(class, "private_get", Mut)),
      #("private_set", HostOp(class, "private_set", Mut)),
      #("private_field_add", HostOp(class, "private_field_add", MutUnit)),
      #("private_in", HostOp(class, "private_in", Read)),
      #("super_get", HostOp(class, "super_get", Mut)),
      #("super_set", HostOp(class, "super_set", Mut)),
      #("super_call", HostOp(class, "super_call", Mut)),
      #("make_method", HostOp(class, "make_method", MutUnit)),
      #("start", HostOp(async, "start", Mut)),
      #("reject", HostOp(async, "reject", Mut)),
      #("gen_start", HostOp(async, "gen_start", Mut)),
      #("asyncgen_start", HostOp(async, "asyncgen_start", Mut)),
      #("math_sqrt", HostOp(math_ffi, "math_sqrt", Pure)),
      #("math_floor", HostOp(math_ffi, "math_floor", Pure)),
      #("math_abs", HostOp(math_ffi, "math_abs", Pure)),
      #("math_pow", HostOp(math_ffi, "math_pow", Pure)),
      #("math_min", HostOp(math_ffi, "math_min", Pure)),
      #("math_max", HostOp(math_ffi, "math_max", Pure)),
    ]),
  )
}
